# Perfil del Banco B.
server:
  port: 8082

banco:
  id: BANCO_B
  nombre: Banco B
  prioridad: 2
  data-file: ${BANCO_DATA_DIR:./data}/cuentas-bancoB.json
  seed-resource: data/cuentas-bancoB.json
  # Los otros dos bancos (peers): A y C.
  peers:
    - id: BANCO_A
      url: ${PEER_A_URL:http://localhost:8081}
    - id: BANCO_C
      url: ${PEER_C_URL:http://localhost:8083}
  replicacion:
    destino-peer-id: BANCO_C
    replicas-dir: ${BANCO_REPLICAS_DIR:./data/replicas}
