# Perfil del Banco C.
server:
  port: 8083

banco:
  id: BANCO_C
  nombre: Banco C
  prioridad: 3
  data-file: ${BANCO_DATA_DIR:./data}/cuentas-bancoC.json
  seed-resource: data/cuentas-bancoC.json
  # Los otros dos bancos (peers): A y B.
  peers:
    - id: BANCO_A
      url: ${PEER_A_URL:http://localhost:8081}
    - id: BANCO_B
      url: ${PEER_B_URL:http://localhost:8082}
  replicacion:
    destino-peer-id: BANCO_A
    replicas-dir: ${BANCO_REPLICAS_DIR:./data/replicas}
